apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service


spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
      - name: product-service
        image: acrganeshdevops001.azurecr.io/product-service:v5

        ports:
        - containerPort: 8080

        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: product-config
              key: APP_NAME

        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: product-config
              key: ENVIRONMENT

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: DB_PASSWORD

        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: API_KEY

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5