name: Build Product Service

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: product-service

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Give Execute Permission
      run: chmod +x mvnw

    - name: Build Application
      run: ./mvnw clean package

    - name: Build Docker Image
      run: |
        docker build -t product-service:${{ github.run_number }} .


        
    - name: Azure Login
      uses: azure/login@v2
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
             az aks get-credentials \
             --resource-group rg-microservices-dev \
              --name aks-microservices-dev \
              --overwrite-existing

    - name: Login to ACR
      run: |
        az acr login --name acrganeshdevops001

    - name: Tag Docker Image
      run: |
        docker tag product-service:${{ github.run_number }} acrganeshdevops001.azurecr.io/product-service:${{ github.run_number }}

    - name: Push Docker Image
      run: |
        docker push acrganeshdevops001.azurecr.io/product-service:${{ github.run_number }}
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.AKS_KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/product-service \
        product-service=acrganeshdevops001.azurecr.io/product-service:${{ github.run_number }}

    - name: Verify Rollout
      run: |
        kubectl rollout status deployment/product-service