name: Build Product Service

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: product-service

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Give Execute Permission
      run: chmod +x mvnw

    - name: Build Application
      run: ./mvnw clean package
    - name: Build Docker Image
      run: |
       docker build -t product-service:${{ github.run_number }} .